### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [compactcoder/QuickNotepad#1]
Traceback (most recent call last):
  File "d:\PROJECT\QuickNotepad-master\QuickNotepad-master\main.py", line 12, in <module>
    title_icon = PhotoImage(file='icons/Titleicon.png')
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 4061, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 4006, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "icons/Titleicon.png": no such file or directory

**Comment by compactcoder** [comment]
@vrindavyas10 
Have you downloaded icons folder ?
If u did not download, download it and place it in folder where your main.py located.

If you downloaded and still not working, you may need to install pillow module in your system.

**Comment by ghost** [comment]
Yes i did both but still getting error

**Comment by compactcoder** [comment]
@vrindavyas10 
It's strange. I have tried in two machines It's working without any error or issue.
Which OS and Python version are you using?

**Comment by ghost** [comment]
Windows python v3.8.2

**Comment by compactcoder** [comment]
I think something messed around icons folder or icons PNG files, like typo in folder or file name etc.  main.py file is not getting path of Titleicon.png

Check if any capital alphabet in your  'icons' folder name. I did this kind of small mistakes in past, so please check it.

Can you share snapshot of QuickNotepad - master file like this where main.py and other files are shown.
![Screenshot (147)](https://user-images.githubusercontent.com/66124951/83326598-f48c9400-a292-11ea-856d-184d82693c60.png)
